# Generated by Django 6.0 on 2025-12-09 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='opening_date',
            field=models.DateField(),
        ),
    ]
