# Generated by Django 5.2.8 on 2025-11-16 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='felling_point',
            new_name='feeling_point',
        ),
    ]
