# Generated by Django 5.2.8 on 2025-11-16 20:03

import django.core.validators
import posts.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_rename_felling_point_post_feeling_point'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(validators=[django.core.validators.MinLengthValidator(10, message='Content must be at least 10 characters long.')]),
        ),
        migrations.AlterField(
            model_name='post',
            name='feeling',
            field=models.CharField(max_length=80, validators=[posts.validators.validate_feeling_text]),
        ),
        migrations.AlterField(
            model_name='post',
            name='feeling_point',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0, message='Feeling point must be at least 0.'), django.core.validators.MaxValueValidator(10, message='Feeling point cannot exceed 10.')]),
        ),
    ]
